import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {RxDropdownMenu} from 'react-icons/rx'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footor />
      </body>
    </html>
  );
}
function Header(){
  const titles = [
    {
      title: "Blogs",
    },
    {
      title: "Pricing",
    },
    {
      title: "Help Center",
    },
    {
      title: "Product Roadmap",
    },
    {
      title: "Twitter",
    },
    {
      title: "Privacy",
    },
    {
      title: "Terms of Service",
    },
  ];
  return(
    <div className="bg-white flex justify-between py-[2%] px-[3%]">
      <div className="">
        <div className="flex"><RxDropdownMenu className="w-16 h-16 "/><h1 className="text-5xl pt-[3%] text-black">Scribe</h1></div>
        <p className="text-xl font-light text-black/75">Email signature made Smart & Sexy</p>
      </div>
      <div className="space-x-[5%] flex text-xl pt-[2%] text-white">
        <button className="text-blue-700 hover:text-white  w-[140px] rounded-xl hover:bg-blue-700">Login</button>
        <button className="text-blue-700 px-[5%] py-[1%] w-[140px] rounded-xl hover:text-white hover:bg-blue-700">Sign up</button>
      </div>
    </div>
  )
}
function Footor() {
  const titles = [
    {
      title: "Blogs",
    },
    {
      title: "Pricing",
    },
    {
      title: "Help Center",
    },
    {
      title: "Product Roadmap",
    },
    {
      title: "Twitter",
    },
    {
      title: "Privacy",
    },
    {
      title: "Terms of Service",
    },
  ];
  return (
    <div className="bg-blue-800 h-full flex justify-between py-[5%] px-[3%]">
      <div className="text-white">
        <div className="flex"><RxDropdownMenu className="w-16 h-16"/><h1 className="text-4xl pt-[5%]">Scribe</h1></div>
        <p className="text-xl font-light">Email signature made Smart & Sexy</p>
      </div>
      <div className="space-x-[5%] w-[65%] text-white text-xl pt-[3%]">
         {titles.map((item,index)=>{
          return <span key={index}>
            {item.title}
          </span>
         })}
      </div>
    </div>
  );
}
